from .MainPage import MainPage
from .ProductPage import ProductPage
from .UserLoginPage import UserLoginPage
from .CatalogPage import CatalogPage
from .AdminLoginPage import AdminLoginPage
from .AdminPage import AdminPage
from .AdminProductsPage import AdminProductsPage
from .RestorePassPage import RestorePassPage
from .BasePage import BasePage
